
services:
  api-service:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - '8082:8081'
    networks:
      - backend

networks:
  backend:
    driver: bridge
