spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/JPATayJava
    #username: ${POSTGRES_USER:postgres}
    #password: ${POSTGRES_PASSWORD:password}
    username: postgres
    password: 2003
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:29092
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    serverName: Server Dev
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: 1.0.0