server:
  port: 8080
spring:
  config:
    activate:
      on-profile: prod

openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    serverName: Server Prod
    title: API Document
    version: 1.0.0